'use client';

import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { motion, MotionConfig } from 'framer-motion';
import { profile } from '@/data/profile';
import { experience } from '@/data/experience';
import { currentLearning, skills } from '@/data/skills';
import { projects } from '@/data/projects';
import { education } from '@/data/education';
import { publications } from '@/data/publications';
import { achievements } from '@/data/achievements';
import { cloud, databaseMatrix } from '@/data/cloud';
import { research } from '@/data/research';
import type { Project } from '@/data/projects';

const nav = [['about','About'],['experience','Experience'],['skills','Skills'],['projects','Projects'],['systems','Systems'],['ai','AI / ML'],['security','Security'],['research','Research'],['education','Education'],['github','GitHub'],['contact','Contact']];
const journey = ['Computer science', 'Database engineering', 'Performance engineering', 'AI / machine learning', 'Cybersecurity', 'Research & R&D'];
function Eyebrow({children,code}:{children:React.ReactNode;code:string}) { return <div className="eyebrow"><span>{code}</span><i />{children}</div> }
function SectionHead({id,number,identity,title,children}:{id:string;number:string;identity:string;title:string;children:string}) { return <div className="section-head" aria-labelledby={id}><Eyebrow code={number}>{identity}</Eyebrow><h2 id={id}>{title}</h2><p>{children}</p></div> }

export default function Home() {
 const [menu,setMenu]=useState(false), [active,setActive]=useState('home'), [selectedProject,setSelectedProject]=useState<Project|null>(null), [researchTopic,setResearchTopic]=useState(research.topics[0]);
 const modalCloseRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{ const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-35% 0px -55%'}); document.querySelectorAll('main section[id], header[id]').forEach(el=>obs.observe(el)); return ()=>obs.disconnect(); },[]);
 useEffect(()=>{ if(!selectedProject)return; const previous=document.activeElement as HTMLElement|null; modalCloseRef.current?.focus(); const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelectedProject(null);return} if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLElement>('.project-modal button,.project-modal a[href]'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}; window.addEventListener('keydown',close); document.body.style.overflow='hidden'; return ()=>{window.removeEventListener('keydown',close);document.body.style.overflow='';previous?.focus()} },[selectedProject]);
 const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.65,ease:[.22,1,.36,1] as const}};
 return <MotionConfig reducedMotion="user"><>
  <a className="skip" href="#main">Skip to content</a>
  <nav className="nav" aria-label="Main navigation"><a className="wordmark" href="#home" aria-label="Papineni Sai Sharan, home"><Image src="/profile.jpg" alt="" width={38} height={38} className="brand-portrait" priority/><b>SAI SHARAN<small>ENGINEER · RESEARCHER</small></b></a><button className={`menu-toggle ${menu?'open':''}`} onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}><i/><i/></button><div className={`nav-links ${menu?'shown':''}`}>{nav.map(([id,label])=><a key={id} className={active===id?'active':''} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</div><a href={`mailto:${profile.email}`} className="nav-contact">LET’S TALK <span>↗</span></a></nav>
  <main id="main">
   <header id="home" className="hero section-tone red"><div className="hero-grid"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="hero-glow"/><div className="hero-content"><Eyebrow code="01 / THE WILL">WILL · CONQUEROR’S HAKI</Eyebrow><motion.p className="hero-kicker" {...reveal}>DATABASE ENGINEERING <span>→</span> AI / ML <span>→</span> CYBERSECURITY</motion.p><h1>PAPINENI<br/><em>SAI SHARAN</em><sup>®</sup></h1><div className="hero-lower"><p className="hero-sub">AI/ML <span className="slash">/</span> CYBERSECURITY</p><div><p className="hero-description">Associate Database Engineer building toward AI/ML, cybersecurity, and research-driven engineering.</p><p className="hero-intro">Computer Science Engineer with production experience in database performance and reliability, alongside hands-on machine learning and cybersecurity research.</p></div></div><div className="hero-actions"><a className="button button-light" href="#about">EXPLORE MY JOURNEY <span>↓</span></a><a className="button button-ghost" href={profile.github} target="_blank" rel="noreferrer">VIEW GITHUB <span>↗</span></a><a className="text-link" href={profile.linkedin} target="_blank" rel="noreferrer">LINKEDIN ↗</a></div></div><div className="hero-side"><span>FIG. 001</span><span>BUILT ON CURIOSITY<br/>TESTED IN PRODUCTION</span><span>BENGALURU · IN</span></div><div className="hero-bottom"><span>SCROLL TO EXPLORE</span><div className="scroll-line"/><span>13° 00′ 12.0″ N / 77° 34′ 48.0″ E</span></div><div className="hero-stamp">覇<br/><small>THE WILL</small></div></header>

   <section id="about" className="section section-tone green"><div className="container"><SectionHead id="about-heading" number="02 / THE DISCIPLINE" identity="Persistence & mastery" title="THE PATH IS NEVER STRAIGHT.">A computer-science foundation, sharpened by production database work, with practical machine-learning experience and cybersecurity research shaping the next direction.</SectionHead><div className="about-layout"><motion.div className="about-copy" {...reveal}><span className="quote-mark">“</span><p>{profile.summary}</p><div className="about-meta"><div><small>BASED IN</small><b>{profile.location}</b></div><div><small>CURRENT ROLE</small><b>{profile.title} · {profile.company}</b></div></div></motion.div><div className="journey"><div className="journey-label">THE COURSE SO FAR <span>01—06</span></div>{journey.map((item,i)=><motion.div key={item} className="journey-step" {...reveal} transition={{delay:i*.04}}><span className="journey-index">0{i+1}</span><span>{item}</span><i>{i===0?'●':'↗'}</i></motion.div>)}</div></div></div><span className="section-watermark">DISCIPLINE</span></section>

   <section id="experience" className="section section-tone violet"><div className="container"><SectionHead id="experience-heading" number="03 / PRECISION" identity="Dracule Mihawk · Precision" title="BUILT FOR THE REAL WORLD.">{experience[0].summary}</SectionHead><div className="experience-layout"><motion.div className="experience-card" {...reveal}><div className="card-top"><span className="pill">PROFESSIONAL EXPERIENCE</span><span className="card-index">01 / 01</span></div><p className="date">{experience[0].dates}</p><h3>{experience[0].role}</h3><p className="company">{experience[0].company}<span> / </span>{experience[0].location}</p><div className="rule"/><div className="experience-context"><div><small>DATABASE HEALTH</small><p>Monitor MySQL · PostgreSQL · TiDB · MongoDB</p></div><div><small>QUERY PERFORMANCE</small><p>Execution-plan analysis · Query optimization · Resource & storage analysis</p></div><div><small>RELIABILITY</small><p>Replication · Monitoring · Production troubleshooting</p></div></div><ul>{experience[0].highlights.map(x=><li key={x}>{x}</li>)}</ul><div className="tags">{experience[0].stack.map(x=><span key={x}>{x}</span>)}</div></motion.div><div className="outcomes"><div className="outcomes-label">SELECTED RESULTS <span>↘</span></div>{experience[0].resultDetails.map((r,i)=><motion.article className="outcome outcome-detail" key={r.title} {...reveal}><b>{r.value}</b><h3>{r.title}</h3><p><strong>WHAT CHANGED</strong>{r.action}</p><p><strong>WHY IT MATTERED</strong>{r.impact}</p></motion.article>)}</div></div><div className="workflow-block"><div className="workflow-heading"><div><Eyebrow code="DATABASE PERFORMANCE ROUTINE">PRECISION THROUGH OBSERVATION</Eyebrow><h3>HOW I APPROACH A PERFORMANCE ISSUE.</h3></div><p>Observe system behavior, isolate bottlenecks, and measure the effect of each improvement.</p></div><div className="workflow-steps">{experience[0].workflow.map((s,i)=><motion.div key={s.name} className="workflow-step" title={s.detail} {...reveal}><span>0{i+1}</span><b>{s.name}</b><small>{s.detail}</small></motion.div>)}</div></div></div><span className="section-watermark">PRECISION</span></section>

   <section id="skills" className="section section-tone crimson"><div className="container"><SectionHead id="skills-heading" number="04 / PRESENCE" identity="Presence · Technical practice" title="A TOOLKIT, EARNED IN CONTEXT.">A practical toolkit shaped by production database engineering, machine-learning work, and cybersecurity research.</SectionHead><div className="skill-grid">{skills.map((group,i)=><motion.article className="skill-group" key={group.name} {...reveal}><div className="skill-group-top"><span>0{i+1}</span><small>{group.evidence}</small></div><h3>{group.name}</h3><p className="skill-detail">{group.detail}</p><div className="skill-items">{group.items.map(x=><span key={x}>{x}</span>)}</div></motion.article>)}</div></div><span className="section-watermark">MASTERY</span></section>

   <section id="projects" className="section section-tone amber"><div className="container"><SectionHead id="projects-heading" number="05 / EXPERIMENTATION" identity="Research & projects · Experimentation" title="QUESTIONS WORTH CHASING.">Two projects apply machine learning to intrusion detection, explainability, and security: one peer-reviewed study and one personal project.</SectionHead><div className="project-map"><div className="map-coordinate">PUBLIC REPOSITORIES<br/>RESEARCH ARCHIPELAGO</div><div className="route route-one"/><div className="route route-two"/><button className="map-node node-one" onClick={()=>setSelectedProject(projects[0])} aria-label="View cross-domain threat detection project">01<i/></button><button className="map-node node-two" onClick={()=>setSelectedProject(projects[1])} aria-label="View machine learning keylogger detection project">02<i/></button><div className="map-caption">SELECT AN ISLAND<br/>TO OPEN FIELD NOTES</div></div><div className="project-list">{projects.map((p,i)=><motion.article className="project-row" key={p.title} {...reveal}><div className="project-row-index">0{i+1}<span>{p.category}</span></div><div className="project-row-copy"><div className="project-card-top"><span>{p.status}</span><span>GITHUB REPOSITORY</span></div><h3>{p.title}</h3><p>{p.summary}</p><div className="tags">{p.technologies.slice(0,6).map(x=><span key={x}>{x}</span>)}</div></div><button className="project-open" onClick={()=>setSelectedProject(p)} aria-label={`Open details for ${p.title}`}>↗<small>OPEN<br/>DETAILS</small></button></motion.article>)}</div><a className="button button-ghost project-all" href={`${profile.github}?tab=repositories`} target="_blank" rel="noreferrer">EXPLORE ALL PUBLIC REPOSITORIES <span>↗</span></a></div><span className="section-watermark">DISCOVERY</span></section>

   <section id="systems" className="section section-tone purple"><div className="container"><SectionHead id="systems-heading" number="06 / INFRASTRUCTURE" identity="Database & systems engineering" title="UNDER THE SURFACE.">Production database engineering grounds my systems perspective: understand the query, inspect the execution plan, and follow the signals through storage, replication, and monitoring.</SectionHead><div className="systems-layout"><div><div className="system-flow">{['APPLICATION','QUERY','QUERY ANALYSIS','EXECUTION PLAN','DATABASE ENGINE','STORAGE','REPLICATION','MONITORING'].map((x,i)=><motion.div key={x} className="flow-node" {...reveal}><span>0{i+1}</span><b>{x}</b><i>{i===0?'↘':'↓'}</i></motion.div>)}</div><p className="architecture-note">DATABASE PERFORMANCE WORKFLOW</p></div><motion.div className="systems-note" {...reveal}><Eyebrow code="PRODUCTION CONTEXT">THE SIGNALS I FOLLOW</Eyebrow><h3>Performance lives in the details.</h3><p>I work with database health, query behavior, execution plans, replication, resource and storage analysis, and production troubleshooting.</p><div className="tags">{['MySQL','PostgreSQL','TiDB','MongoDB'].map(x=><span key={x}>{x}</span>)}</div><div className="lab-note"><span>PERSONAL LABS</span><p>My independent projects explore machine learning and security research.</p></div></motion.div></div><div className="cloud-heading"><Eyebrow code="CLOUD / DATABASE INFRASTRUCTURE">AWS CLOUD · DATABASE & COMPUTE</Eyebrow><p>AWS EC2, RDS, and Aurora extend my cloud and database toolkit.</p></div><div className="cloud-grid">{cloud.map((item,i)=><motion.article className="cloud-item" key={item.name} {...reveal}><span>0{i+1} / {item.label}</span><h3>{item.name}</h3><p>{item.detail}</p></motion.article>)}</div><div className="cloud-architecture"><div className="cloud-architecture-label">CLOUD DATABASE WORKFLOW</div><div>{['APPLICATION','AWS','EC2','RDS / AURORA','MONITORING','PERFORMANCE / RELIABILITY'].map((x,i)=><span key={x}>{x}{i<5&&<i>↓</i>}</span>)}</div></div><div className="matrix"><div className="eyebrow"><span>TECHNOLOGY MATRIX</span><i/>DATABASES · SYSTEMS · PERFORMANCE</div>{databaseMatrix.map(row=><div className="matrix-row" key={row.category}><b>{row.category}</b><div><p>{row.context}</p><div className="tags">{row.items.map(x=><span key={x}>{x}</span>)}</div></div></div>)}</div></div><span className="section-watermark">FOUNDATION</span></section>

   <section id="ai" className="section section-tone ice"><div className="container"><SectionHead id="ai-heading" number="07 / THE NEXT FRONTIER" identity="Whitebeard · The Next Frontier" title="FROM DATA TO EXPLANATION.">Hands-on work across ML/DL model development, evaluation, ensemble methods, and explainability with SHAP and LIME.</SectionHead><div className="pipeline">{['DATA','PREPROCESSING','FEATURE ENGINEERING','MODEL DEVELOPMENT','EVALUATION','ENSEMBLES','EXPLAINABILITY','INTERPRETATION'].map((x,i)=><motion.div key={x} className="pipeline-node" {...reveal}><span>0{i+1}</span><b>{x}</b>{i<7&&<i>→</i>}</motion.div>)}</div><div className="ai-foot"><span>SUPERVISED LEARNING</span><span>DEEP LEARNING</span><span>ENSEMBLE MODELS</span><span>MODEL EVALUATION</span><span>BENCHMARKING</span></div><div className="xai-row"><motion.article {...reveal}><span>EXPLAINABLE AI / 01</span><h3>SHAP</h3><p>Used for model interpretation and examining feature importance.</p></motion.article><motion.article {...reveal}><span>EXPLAINABLE AI / 02</span><h3>LIME</h3><p>LIME helps interpret individual model predictions.</p></motion.article></div><div className="learning-panel"><div><Eyebrow code="CURRENT LEARNING">AREAS OF PRACTICE</Eyebrow><p>Areas I’m exploring alongside my current engineering and research work.</p></div><div className="learning-lanes"><div><small>AI / ML</small><div className="tags">{currentLearning.ai.map(x=><span key={x}>{x}</span>)}</div></div><div><small>SECURITY</small><div className="tags">{currentLearning.security.map(x=><span key={x}>{x}</span>)}</div></div><div><small>RESEARCH</small><div className="tags">{currentLearning.research.map(x=><span key={x}>{x}</span>)}</div></div></div></div></div><span className="section-watermark">KNOWLEDGE</span></section>

   <section id="security" className="section section-tone blue"><div className="container"><SectionHead id="security-heading" number="08 / THE SECURITY" identity="Rayleigh · Technique" title="READ THE SIGNAL. FIND THE THREAT.">My cybersecurity work combines machine learning and threat detection to study network behavior across IIoT and Darknet environments.</SectionHead><div className="security-path">{['NETWORK / SYSTEM DATA','PREPROCESSING','FEATURE ENGINEERING','MACHINE LEARNING','THREAT DETECTION','EXPLAINABILITY','INTERPRETATION'].map((x,i)=><motion.div key={x} className="security-step" {...reveal}><span>0{i+1}</span><b>{x}</b></motion.div>)}</div><div className="security-note"><span>RESEARCH CONNECTION</span><p>Cross-domain intrusion detection · CIC-APT-IIoT-2024 · CIC-Darknet2020 · SHAP · LIME</p></div><a className="section-inline-link" href="#research">EXPLORE THE RESEARCH <span>↓</span></a></div><span className="section-watermark">VIGILANCE</span></section>

   <section id="research" className="section section-tone gold"><div className="container"><SectionHead id="research-heading" number="09 / THE DISCOVERY" identity="Gol D. Roger · Discovery" title="THE JOURNEY IS NOT OVER.">{research.summary}</SectionHead><div className="current-research"><div><span>CURRENT RESEARCH · EXPLORATION</span><h3>{research.profileListedCurrent.title}</h3><p>{research.profileListedCurrent.question}</p></div><div><small>{research.profileListedCurrent.status}</small><div className="tags">{research.profileListedCurrent.topics.map(x=><span key={x}>{x}</span>)}</div></div></div><div className="research-status"><span>PUBLICATION / {research.status.toUpperCase()}</span><p>My research examines cross-domain intrusion detection through model evaluation and explainable AI.</p></div><div className="research-map"><div className="research-orbit"><i/><i/><i/><i/><i/><i/></div><div className="research-nodes">{research.topics.map((t,i)=><button key={t.name} className={researchTopic.name===t.name?'selected':''} onClick={()=>setResearchTopic(t)}><span>0{i+1}</span>{t.name}</button>)}</div><div className="research-focus"><Eyebrow code="RESEARCH CONNECTION">{researchTopic.name}</Eyebrow><p>{researchTopic.detail}</p><a href={researchTopic.name==='CROSS-CHIP'?profile.github:projects[0].href} target="_blank" rel="noreferrer">{researchTopic.name==='CROSS-CHIP'?'VIEW RESEARCH DIRECTION ↗':'VIEW THE RESEARCH ↗'}</a></div></div><div className="publication"><div className="pub-top"><span>PEER-REVIEWED PUBLICATION</span><span>IEEE · ICDDS 2025</span></div><h3>{publications[0].title}</h3><p className="authors">{publications[0].authors.join(' · ')}</p><p className="venue">{publications[0].venue} <span>/</span> {publications[0].date}</p><div className="publication-detail"><div><small>DATASETS</small><p>{publications[0].datasets.join(' · ')}</p></div><div><small>METHODS</small><p>{publications[0].methods.join(' · ')}</p></div><div><small>PROCESS</small><p>{publications[0].process.join(' · ')}</p></div></div><div className="pub-results">{publications[0].results.map(x=><div key={x.label}><b>{x.value}</b><span>{x.label}</span></div>)}</div><div className="metrics-key"><small>EVALUATION METRICS</small>{publications[0].metrics.map(x=><p key={x.name}><b>{x.name}</b><span>{x.detail}</span></p>)}</div><div className="pub-methods">{publications[0].process.map((x,i)=><span key={x}>{String(i+1).padStart(2,'0')} / {x}</span>)}</div><div className="pub-bottom"><span>DOI&nbsp; {publications[0].doi}</span><a className="button button-light" href={publications[0].href} target="_blank" rel="noreferrer">READ PAPER <span>↗</span></a></div></div><div className="research-workflow"><Eyebrow code="RESEARCH WORKFLOW">FROM DATA TO INTERPRETATION</Eyebrow><div>{research.workflow.map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div></div><span className="section-watermark">THE UNKNOWN</span></section>

    <section id="education" className="section section-tone sky"><div className="container"><SectionHead id="education-heading" number="10 / THE GROWTH" identity="Koby · Growth" title="GROWTH IS A PRACTICE.">Built a foundation in computer science that led into database engineering, machine learning, cybersecurity, and research.</SectionHead><div className="education-timeline"><div className="education-record"><div className="edu-record-date">{education[0].dates}<span>EDUCATION / 01</span></div><div><h3>{education[0].degree}<br/><em>{education[0].field}</em></h3><p>{education[0].institution} · {education[0].location}</p></div></div><div className="education-path">{education[0].progression.map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div><motion.article className="achievement-line" {...reveal}><div><span>PERSONAL MILESTONE · {achievements[0].date}</span><h3>{achievements[0].title}</h3></div><p>{achievements[0].description}</p></motion.article></div><span className="section-watermark">BECOMING</span></section>

   <section id="github" className="section section-tone blue"><div className="container"><SectionHead id="github-heading" number="11 / THE CODE" identity="Trafalgar Law · The Code" title="OPEN SOURCE OF THE JOURNEY.">Selected public projects in machine learning, explainable AI, and cybersecurity research.</SectionHead><div className="github-ledger">{projects.map((p,i)=><motion.article className="github-entry" key={p.title} {...reveal}><span className="github-entry-index">0{i+1}<small>{p.category}</small></span><div><h3>{p.title}</h3><p>{p.summary}</p><div className="tags">{p.technologies.slice(0,6).map(x=><span key={x}>{x}</span>)}</div></div><a href={p.href} target="_blank" rel="noreferrer" aria-label={`Open ${p.title} on GitHub`}>↗</a></motion.article>)}</div><div className="github-bottom"><p>More experiments and source code are available on GitHub.</p><a className="button button-light" href={`${profile.github}?tab=repositories`} target="_blank" rel="noreferrer">ENTER MY CODEBASE <span>↗</span></a></div></div><span className="section-watermark">THE CODE</span></section>

   <section className="resume-band"><div><Eyebrow code="12 / THE RECORD">CLEAR, COMPLETE, CURRENT</Eyebrow><h2>THE FULL PICTURE.</h2><p>Experience, research, education, and skills in one place.</p></div><a className="button button-light" href={profile.resume} target="_blank" rel="noreferrer">VIEW RESUME <span>↗</span></a><a className="button button-ghost" href={profile.resume} download>DOWNLOAD <span>↓</span></a></section>

   <section id="contact" className="contact section-tone red"><div className="horizon"/><div className="ship"><i/><span/></div><div className="container contact-content"><Eyebrow code="13 / THE NEXT VOYAGE">OPEN TO MEANINGFUL ENGINEERING</Eyebrow><h2>READY TO BUILD<br/><em>SOMETHING?</em></h2><p>Database engineer. Researcher. Builder.<br/>Let’s talk about what comes next.</p><a className="email-link" href={`mailto:${profile.email}`}>{profile.email}<span>↗</span></a><div className="contact-actions"><a className="button button-light" href={`mailto:${profile.email}`}>EMAIL ME <span>↗</span></a><a className="button button-ghost" href={profile.github} target="_blank" rel="noreferrer">VIEW GITHUB <span>↗</span></a><a className="button button-ghost" href={profile.linkedin} target="_blank" rel="noreferrer">LINKEDIN <span>↗</span></a><a className="button button-ghost" href={profile.resume} target="_blank" rel="noreferrer">VIEW RESUME <span>↗</span></a></div></div><footer><a className="wordmark" href="#home"><span>PS</span><b>SAI SHARAN<small>ENGINEER · RESEARCHER</small></b></a><p>THE ADVENTURE CONTINUES.</p><span>© {new Date().getFullYear()} PAPINENI SAI SHARAN · BENGALURU</span></footer><span className="section-watermark">FORWARD</span></section>
  </main>
  {selectedProject&&<div className="project-modal-backdrop" role="presentation" onClick={()=>setSelectedProject(null)}><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title" aria-describedby="project-modal-summary" onClick={e=>e.stopPropagation()}><div className="project-modal-top"><span>{selectedProject.category} · {selectedProject.status}</span><button ref={modalCloseRef} onClick={()=>setSelectedProject(null)} aria-label="Close project details">CLOSE ×</button></div><h2 id="project-modal-title">{selectedProject.title}</h2><p id="project-modal-summary" className="project-modal-summary">{selectedProject.summary}</p><div className="project-detail-grid"><div><small>01 / CONTEXT</small><p>{selectedProject.category}</p></div><div><small>02 / PROBLEM</small><p>{selectedProject.problem}</p></div><div><small>03 / APPROACH</small><p>{selectedProject.approach}</p></div>{selectedProject.datasets&&<div><small>04 / DATASETS</small><p>{selectedProject.datasets.join(' · ')}</p></div>}<div><small>05 / IMPLEMENTATION</small><ul>{selectedProject.implementation.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>06 / TECHNOLOGIES</small><p>{selectedProject.technologies.join(' · ')}</p></div>{selectedProject.results&&<div><small>07 / REPORTED RESULTS</small><ul>{selectedProject.results.map(x=><li key={x}>{x}</li>)}</ul></div>}</div><a className="button button-light" href={selectedProject.href} target="_blank" rel="noreferrer">OPEN SOURCE REPOSITORY <span>↗</span></a></section></div>}
 </></MotionConfig>
}
